### ISSUE TITLE
Add BlobStorage to BlobStorage stream

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/arcane-framework#62]
I'd like to have a stream plugin that allows streaming files from on Blob to another, for examples S3 -> MinIO, S3 -> S3, Azure -> S3 etc. For starters no need to support sinking into Parquet or other formats, basically just move bytes from one storage to another. YAML spec can be something like:

```
spec:
  blobSource:
    s3:
      bucket: mybucket
      prefix: myprefix/data
    azure:
       container: my-container
       prefix: myprefix/data
  blobTarget:
    s3:
      bucket: mybucket
      prefix: myprefix/data
    azure:
       container: my-container
       prefix: myprefix/data
```

- [x] SneaksAndData/arcane-framework#69
- [x] SneaksAndData/arcane-framework#70
- [x] SneaksAndData/arcane-stream-blob-storage#5
- [x] SneaksAndData/terraform#2888
- [x] SneaksAndData/terraform#2890
- [x] SneaksAndData/arcane-stream-blob-storage#27
- [ ] Add Azure support

**Comment by s-vitaliy** [comment]
- [ ] Implement generic blob storage in Arcane.Framework
- [ ] Implement generic blob storage sink in Arcane.Framework
- [ ] Create repository and implement blob storage stream plugin
- [ ] Deploy stream plugin on production
- [ ] Add source S3 bucket
